name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Droplet via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 137.184.161.71
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd TitanSwarm
            git pull origin master
            docker compose up -d --build
