[theme]
base="light"
primaryColor = "#6366f1"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f1f5f9"
textColor = "#0f172a"
font = "sans serif"

[server]
runOnSave = false
enableCORS = true
enableXsrfProtection = true
port = 8501
headless = true

[ui]
